import type { Template } from '@/types/template';

// Seed data for free templates (5 types)
// canvasData will be populated properly when Supabase is set up
export const FREE_TEMPLATE_SEEDS: Omit<Template, 'canvasData'>[] = [
  {
    id: 'tpl_birthday_simple',
    slug: 'birthday-simple',
    category: 'birthday',
    style: 'simple',
    name: 'シンプル誕生日',
    thumbnailUrl: '/templates/birthday-simple.jpg',
    isPremium: false,
    tags: ['birthday', 'シンプル', 'ミニマル'],
    sortOrder: 1,
  },
  {
    id: 'tpl_birthday_pop',
    slug: 'birthday-pop',
    category: 'birthday',
    style: 'pop',
    name: 'ポップ誕生日',
    thumbnailUrl: '/templates/birthday-pop.jpg',
    isPremium: false,
    tags: ['birthday', 'ポップ', 'カラフル'],
    sortOrder: 2,
  },
  {
    id: 'tpl_thank_you_elegant',
    slug: 'thank-you-elegant',
    category: 'thank_you',
    style: 'elegant',
    name: 'エレガントお礼',
    thumbnailUrl: '/templates/thank-you-elegant.jpg',
    isPremium: false,
    tags: ['thank_you', 'エレガント', 'フォーマル'],
    sortOrder: 3,
  },
  {
    id: 'tpl_congratulations_cool',
    slug: 'congratulations-cool',
    category: 'congratulations',
    style: 'cool',
    name: 'クールお祝い',
    thumbnailUrl: '/templates/congratulations-cool.jpg',
    isPremium: false,
    tags: ['congratulations', 'クール', 'スタイリッシュ'],
    sortOrder: 4,
  },
  {
    id: 'tpl_seasonal_simple',
    slug: 'seasonal-simple',
    category: 'seasonal',
    style: 'cute',
    name: 'かわいい季節カード',
    thumbnailUrl: '/templates/seasonal-cute.jpg',
    isPremium: false,
    tags: ['seasonal', 'かわいい', '季節'],
    sortOrder: 5,
  },
  {
    id: 'tpl_wedding_botanical',
    slug: 'wedding-botanical',
    category: 'wedding',
    style: 'elegant',
    name: 'ボタニカルウェディング',
    thumbnailUrl: '/templates/wedding-botanical.jpg',
    isPremium: false,
    tags: ['wedding', 'ボタニカル', 'エレガント'],
    sortOrder: 6,
  },
  {
    id: 'tpl_wedding_gold',
    slug: 'wedding-gold',
    category: 'wedding',
    style: 'elegant',
    name: 'ゴールドモノグラム',
    thumbnailUrl: '/templates/wedding-gold.jpg',
    isPremium: false,
    tags: ['wedding', 'ゴールド', 'フォーマル'],
    sortOrder: 7,
  },
  {
    id: 'tpl_farewell_sunset',
    slug: 'farewell-sunset',
    category: 'congratulations',
    style: 'cool',
    name: '退職・送別カード',
    thumbnailUrl: '/templates/farewell-sunset.jpg',
    isPremium: false,
    tags: ['farewell', '退職', '送別'],
    sortOrder: 8,
  },
  {
    id: 'tpl_farewell_bouquet',
    slug: 'farewell-bouquet',
    category: 'congratulations',
    style: 'cute',
    name: '春のブーケ送別',
    thumbnailUrl: '/templates/farewell-bouquet.jpg',
    isPremium: false,
    tags: ['farewell', 'ブーケ', '花'],
    sortOrder: 9,
  },
  {
    id: 'tpl_thank_you_sage',
    slug: 'thank-you-sage',
    category: 'thank_you',
    style: 'simple',
    name: 'セージグリーンお礼',
    thumbnailUrl: '/templates/thank-you-sage.jpg',
    isPremium: false,
    tags: ['thank_you', 'セージ', 'ナチュラル'],
    sortOrder: 10,
  },
  {
    id: 'tpl_anniversary_romantic',
    slug: 'anniversary-romantic',
    category: 'anniversary',
    style: 'elegant',
    name: 'ロマンティック記念日',
    thumbnailUrl: '/templates/anniversary-romantic.jpg',
    isPremium: false,
    tags: ['anniversary', 'ロマンティック', 'ハート'],
    sortOrder: 11,
  },
  {
    id: 'tpl_birthday_elegant',
    slug: 'birthday-elegant',
    category: 'birthday',
    style: 'elegant',
    name: 'エレガント誕生日',
    thumbnailUrl: '/templates/birthday-elegant.jpg',
    isPremium: false,
    tags: ['birthday', 'エレガント', '大人'],
    sortOrder: 12,
  },
  {
    id: 'tpl_business_formal',
    slug: 'business-formal',
    category: 'business',
    style: 'simple',
    name: 'フォーマルビジネス',
    thumbnailUrl: '/templates/business-formal.jpg',
    isPremium: false,
    tags: ['business', 'フォーマル', 'ビジネス'],
    sortOrder: 13,
  },
  {
    id: 'tpl_seasonal_summer',
    slug: 'seasonal-summer',
    category: 'seasonal',
    style: 'pop',
    name: '夏の爽やかカード',
    thumbnailUrl: '/templates/seasonal-summer.jpg',
    isPremium: false,
    tags: ['seasonal', '夏', '暑中見舞い'],
    sortOrder: 14,
  },
  {
    id: 'tpl_mothers_day',
    slug: 'mothers-day',
    category: 'seasonal',
    style: 'cute',
    name: '母の日カーネーション',
    thumbnailUrl: '/templates/mothers-day.jpg',
    isPremium: false,
    tags: ['seasonal', '母の日', 'カーネーション'],
    sortOrder: 15,
  },
];

export const TEMPLATE_CATEGORY_LABELS: Record<string, string> = {
  birthday: '誕生日',
  wedding: '結婚',
  anniversary: '記念日',
  thank_you: 'お礼',
  congratulations: 'お祝い',
  seasonal: '季節',
  business: 'ビジネス',
};

export const TEMPLATE_STYLE_LABELS: Record<string, string> = {
  cute: 'かわいい',
  elegant: 'エレガント',
  cool: 'クール',
  simple: 'シンプル',
  pop: 'ポップ',
};
